# Generated by Django 6.0.6 on 2026-06-09 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metricapp', '0002_contact_subscribe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribe',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
