# Generated by Django 6.0.6 on 2026-06-09 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metricapp', '0003_alter_subscribe_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='mobile',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
